[project]
name = "fg-endpoint-tools"
version = "0.8.0"
description = "Collection of tools to work with FinnGen endpoints."
readme = "README.md"
authors = [
    { name = "Vincent", email = "me@example.com" }
]
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "gunicorn>=23.0.0",
    "polars[excel]>=1.26.0",
    "xlsxwriter>=3.2.2",
]

[project.scripts]
fg-endpoint-tools = "fg_endpoint_tools:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipython>=9.0.2",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
    "ty>=0.0.0a7",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
